// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateFund(ctx context.Context, arg CreateFundParams) (Fund, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChallengeByID(ctx context.Context, id int32) (Challenge, error)
	GetFundByID(ctx context.Context, id int32) (Fund, error)
	GetGoalByID(ctx context.Context, id int32) (Goal, error)
	GetTaskByID(ctx context.Context, id int32) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserChallengeStatus(ctx context.Context, arg GetUserChallengeStatusParams) (UserChallenge, error)
	JoinChallenge(ctx context.Context, arg JoinChallengeParams) (UserChallenge, error)
	ListActiveChallenges(ctx context.Context) ([]Challenge, error)
	ListFundsByGoalID(ctx context.Context, goalID int32) ([]Fund, error)
	ListGoalsByUserID(ctx context.Context, userID int32) ([]Goal, error)
	ListTasksByGoalID(ctx context.Context, goalID int32) ([]Task, error)
	UpdateFundStatus(ctx context.Context, arg UpdateFundStatusParams) (Fund, error)
	UpdateGoalAmount(ctx context.Context, arg UpdateGoalAmountParams) (Goal, error)
	UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) (Goal, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserChallengeStatus(ctx context.Context, arg UpdateUserChallengeStatusParams) (UserChallenge, error)
	UpdateUserWalletAddress(ctx context.Context, arg UpdateUserWalletAddressParams) (User, error)
}

var _ Querier = (*Queries)(nil)
